sudo: required
language: generic 

services: 
  - docker 

before_install:
  - docker build -t sharmad6/docker-run-test -f Dockerfile.dev .


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker"
  env: "docker-env"
  bucket_name: "elastickbeanstackbuckertpath"
  bucket_path: "docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"