sudo: required
language: generic 

services: 
  - docker 

before_install:
  - docker build -t sharmad6/docker-run-test -f Dockerfile.dev .

script: 
  - docker run -e CI=true sharmad6/docker-run-test sudo npm run test -- --coverage