version: '3'
services: 
    web:
      build: 
        context: .
        dockerfile: Dockerfile.dev
      ports: 
        - "4012:3000"
      volumes:  
        - /usr/app/node_modules
        - .:/usr/app 
